### ISSUE TITLE
Add a --no-clobber option [enhancement]

### ISSUE THREAD

**Issue by jvonhoff** [wlan222/kisscartoon#11]
Would it be possible to add an option to not overwrite existing files?

As noted in another issue, KissCartoon is throwing back errors after 3-4 downloads, and then, if I call kissgrab again, it starts over -- wiping out files that were already successfully downloaded.

Thanks!

**Comment by jafrewa** [comment]
Let's call it --no-overwrite

**Comment by jvonhoff** [comment]
Sure.  I think no-clobber is from wget, but as long as the functionality exists, I'll be happy!

**Comment by jafrewa** [comment]
What OS are you running ?

**Comment by jvonhoff** [comment]
Ubuntu 16.04 LTS.  I can try Arch if that helps.

**Comment by jafrewa** [comment]
Okay nevermind was unsure if I did the path detection correctly for Linux but that wasn't it. I seriously need to rewrite this. It's getting worse and worse maintaining this. Anyways this is added in the next commit ( syncing right now ). As for your other Issue I think I might postpone it for the rewrite since the structure of the application isn't capable of achieving that as of now.

**Comment by jafrewa** [comment]
Took longer than expected but https://github.com/wlan222/kisscartoon/commit/65bd2d0229198a49e1ba7ab0d865c9ff8446aae0 

adds the feature
