### ISSUE TITLE
Write Complete Episodes to kissgrab.dat

### ISSUE THREAD

**Issue by slipsystem** [wlan222/kisscartoon#15]
Hey Man. 

this is not an issue more of a feature request.

it may be a good idea to write complete episodes to the dat file to prevent the script from attempting to redownload the file. then instead of 

`if os.path.isfile(path):`

you can do something like 

`if path in datfile.read():`

at the moment if i move episodes to another location i tries to download them again.

I will try implement this myself and send you the code

**Comment by jafrewa** [comment]
@jvonhoff wrote that feature.

Im currently rewriting kisscartoon (again) and in that version I'll be using JSON files to keep the shows and the links accordingly on your local hard drive. If you run kisscartoon again it will only download the episodes it hasn't downloaded yet and update the show file. 

I have no ETA on the update though since im kinda busy. 

Thank you for contributing!
